version: '3.4'

networks:
  moviesandseries:
    driver: bridge

services:
  moviesandseries.server.api:
    image: ${DOCKER_REGISTRY-}moviesandseriesserverapi
    build:
      context: .
      dockerfile: MoviesAndSeries.Server.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - moviesandseries
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: moviesandseriesdb
    ports:
      - "5432:5432"
    networks:
      - moviesandseries
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: